# Generated by Django 3.1.2 on 2020-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0002_auto_20201105_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='curr_round',
            field=models.IntegerField(default=0),
        ),
    ]
